import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

function jsStringLiteral(value: string): string {
  // JSON string is the simplest safe embedding.
  return JSON.stringify(value);
}

const repoRoot = join(import.meta.dir, "..");
const promptsDir = join(repoRoot, "prompts");

const designerNew = readFileSync(join(promptsDir, "designer_new.md"), "utf-8");
const designerEdit = readFileSync(
  join(promptsDir, "designer_edit.md"),
  "utf-8"
);
const worker = readFileSync(join(promptsDir, "worker.md"), "utf-8");
const reviewTriage = readFileSync(
  join(promptsDir, "review_triage.md"),
  "utf-8"
);

const out = `// This file is generated by scripts/generate_prompts.ts
// Do not edit directly.

export type PromptName = "designer_new" | "designer_edit" | "worker" | "review_triage";

export const BUILTIN_PROMPTS: Record<PromptName, string> = {
  designer_new: ${jsStringLiteral(designerNew)},
  designer_edit: ${jsStringLiteral(designerEdit)},
  worker: ${jsStringLiteral(worker)},
  review_triage: ${jsStringLiteral(reviewTriage)},
};
`;

mkdirSync(join(repoRoot, "src", "lib"), { recursive: true });
writeFileSync(join(repoRoot, "src", "lib", "prompt_sources.ts"), out);
console.log("Generated src/lib/prompt_sources.ts");
